name: Fetch Build Config

on:
  workflow_call:
    inputs:
      zip_url_json:
        required: false
        type: string

jobs:
  download-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Upload config as artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-zip
          path: |
            config/secrets.json
            config/icon.png
            config/logo.png
          retention-days: 1
